// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// smdh_list_div_cpp
List smdh_list_div_cpp(arma::mat X, arma::mat V, arma::vec b, arma::mat mean, arma::vec ss, arma::vec ssss, IntegerVector t_init, double hmult, double C, int t_max, double alpha, arma::vec clusters, arma::vec scl, arma::vec mu0, int scale, int t_init0);
RcppExport SEXP _iMDH_smdh_list_div_cpp(SEXP XSEXP, SEXP VSEXP, SEXP bSEXP, SEXP meanSEXP, SEXP ssSEXP, SEXP ssssSEXP, SEXP t_initSEXP, SEXP hmultSEXP, SEXP CSEXP, SEXP t_maxSEXP, SEXP alphaSEXP, SEXP clustersSEXP, SEXP sclSEXP, SEXP mu0SEXP, SEXP scaleSEXP, SEXP t_init0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ssss(ssssSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type t_init(t_initSEXP);
    Rcpp::traits::input_parameter< double >::type hmult(hmultSEXP);
    Rcpp::traits::input_parameter< double >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type scl(sclSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< int >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< int >::type t_init0(t_init0SEXP);
    rcpp_result_gen = Rcpp::wrap(smdh_list_div_cpp(X, V, b, mean, ss, ssss, t_init, hmult, C, t_max, alpha, clusters, scl, mu0, scale, t_init0));
    return rcpp_result_gen;
END_RCPP
}
// smdh_list_div_pass_cpp
List smdh_list_div_pass_cpp(arma::mat X, arma::mat V, arma::vec b, arma::mat mean, arma::vec ssss, arma::vec scl, arma::vec mu0, int scale);
RcppExport SEXP _iMDH_smdh_list_div_pass_cpp(SEXP XSEXP, SEXP VSEXP, SEXP bSEXP, SEXP meanSEXP, SEXP ssssSEXP, SEXP sclSEXP, SEXP mu0SEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ssss(ssssSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type scl(sclSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< int >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(smdh_list_div_pass_cpp(X, V, b, mean, ssss, scl, mu0, scale));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_iMDH_smdh_list_div_cpp", (DL_FUNC) &_iMDH_smdh_list_div_cpp, 16},
    {"_iMDH_smdh_list_div_pass_cpp", (DL_FUNC) &_iMDH_smdh_list_div_pass_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_iMDH(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
