# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smdh_list_div_cpp <- function(X, V, b, mean, ss, ssss, t_init, hmult, C, t_max, alpha, clusters, scl, mu0, scale, t_init0, q, r) {
    .Call(`_iMDH_smdh_list_div_cpp`, X, V, b, mean, ss, ssss, t_init, hmult, C, t_max, alpha, clusters, scl, mu0, scale, t_init0, q, r)
}

smdh_list_div_pass_cpp <- function(X, V, b, mean, ssss, ts, scl, mu0, scale) {
    .Call(`_iMDH_smdh_list_div_pass_cpp`, X, V, b, mean, ssss, ts, scl, mu0, scale)
}

